name: Terraform Validate

defaults: 
  run:
    working-directory: infrastructure

on:
  workflow_dispatch: 
  push:
    branches:
      - 'dev'
      - 'prod'
    paths:
      - 'infrastructure/**'
  pull_request:
    branches:
      - 'dev'
      - 'prod'
    paths:
      - 'infrastructure/**'

jobs:  
  terraform:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TF_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TF_SECRET_ACCESS_KEY }}
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_TF_ACCESS_KEY }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_TF_SECRET_ACCESS_KEY }}
      TF_VAR_assume_role_target: ${{ secrets.AWS_TF_ASSUME_ROLE_TARGET }}
      TF_VAR_deployment_region: ${{ vars.AWS_TF_DEPLOYMENT_REGION }}
      TF_VAR_domain_name: ${{ vars.AWS_TF_DOMAIN_NAME }}
      TF_VAR_sanitized_domain_name: ${{ vars.AWS_TF_SANITIZED_DOMAIN_NAME }}
      TF_VAR_api_current_stage: ${{ vars.AWS_TF_API_CURRENT_STAGE }}
      TF_VAR_hosted_zone_id: ${{ vars.AWS_TF_HOSTED_ZONE_ID }}

    steps:
      - name: Update Access Token
        uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          permissions: |
            secrets: write
            actions-variables: write        
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          terraform_wrapper: true

      - name: Terraform Format
        id: format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: initialize
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
        env:
          GITHUB_TOKEN: ${{ steps.access-token.outputs.token }}
          TF_VAR_github_token: ${{ steps.access-token.outputs.token }}
