name: Terraform Validate

defaults: 
  run:
    working-directory: infrastructure

on:
  push:
    branches:
      - 'dev'
      - 'prod'
    paths:
      - 'infrastructure/**'
  pull_request:
    branches:
      - 'dev'
      - 'prod'
    paths:
      - 'infrastructure/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      aws_access_key_id: ${{ secrets.AWS_TF_ACCESS_KEY }}
      aws_secret_access_key: ${{ secrets.AWS_TF_SECRET_ACCESS_KEY }}
      assume_role_target: ${{ secrets.AWS_TF_ASSUME_ROLE_TARGET }}
      deployment_region: ${{ vars.AWS_TF_DEPLOYMENT_REGION }}
      domain_name: ${{ vars.AWS_TF_DOMAIN_NAME }}
      sanitized_domain_name: ${{ vars.AWS_TF_SANITIZED_DOMAIN_NAME }}
      api_current_stage: ${{ vars.AWS_TF_API_CURRENT_STAGE }}
      hosted_zone_id: ${{ vars.AWS_TF_HOSTED_ZONE_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          terraform_wrapper: true

      - name: Terraform Format
        id: format
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: initialize
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false